# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_R=3.3.2
    - CONDA_R=3.4.1
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Dtbin1VClI85Yfh1UupWGLVH+iFvYREImWKg4gJ4/N8TxzpdcVzBYsIHwl6FNP0urY4U+O9GAgjrLWVlsGKtc5x79kU1KGacVx9exJQsHvksjnoY9Xupxcw2mCllUe3r6aRQVNpI+6cp6TSsnZZtVSGl9BcR0Oq+HIzFIQ0kz943XA5ax8Xo+75qRhJJlD5d27dXF7HGhumaT5oQEHBByc1SVMuZSBVXcyEpXnWVQ5WGM1N2E+Y3dvvVk4RoLxl8UuYgoaGVsMaQBdT2Ng+1VPIhgZF61P0RBsZTqzihn9bSKnD1Ef73YvROmzemRVPVDOkKs3fnAytSHNEv7JDut4V9qHHPg343zqXzq+8Oj2GII3NgT3CHRYMQBolv4M8nAPWv5ZHX4S/dJXGAPGeyAcXJ2UvwIiCSqQLrXj3FtgiUYHEc2cJgiTWkwdil/ENVBeYUi/2HByL/PhSDFE0pr4GFv0/xuhrLxmvRvOkV6YUZ+Y7D7vV00Om9mV9PdkfO0AqjoGA+p2/+s19fAN3AJQidmMDOoMOPLFVtc+0xCdirB/MhBX1B8yic1YpOH1qCC1+WG85Nw+bD5CdGt3VD374+quByeGyKIdmq/TS8I7HIyUNzZqo9yE2yae2zuf6eX9qKF0jNMFRBVSGCGm9Fp/dpgTJxgA2uUeYENw+/FyU="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
