travis:
  secure:
    BINSTAR_TOKEN: Ruolk1+PfsTwA1RpbeIZ1Ub4OA0Vwsr2Y5q8tz6rxKEfyJxGWP19Wc1205P4ividF3W5OWDBEyR+LSw1N5hZ/34g/gDuDKxLEbOoycrgQZAxDAwZnhn1u5FcHKzXIE57Sd6Sq0u0KHBh45Ct6lP+bsyPed3O7pEdkndMjp4MBp6rAxbcsoNWIWi9fZz6ZPfUQzapRxl5ar/LtSulVABxaNDPPPfHA04iA5M4AFwiPdZ4Aj8TxnfinIXQ+NoG9e/FzO7ZqRsxVioejVo0h+CEBqHCUPn2d6eLxrhppmpvdGymsHk9Y/4W1Kkn8nwHaITCOcfk8h9MD1k0yyKCZJ1XZOXYGi1DftmThkLjwS+OMVdmIfc4mDst7DRSszl2HxP6Cvt5VJo3GKhiW2EfG0iNzJ3iqpu7MWrSbWlZr+R4kNBJH+PBayOges29oOfCTP1qudBpiCouXBEGeTaczo/RvyI3ET3a18E6wO3V7yXpS1cwmTLzJpK4+iG2TLUjXbkPnhtcNZBfF20M9e3XyNtd0lk0Druy5tWBoVCOurZlfnXWJD+xdydWI/tgQcwPEQslZf+7bhnMDv2XDWb7kEHdq6IGmk4/On5X3KW1Ta/VcKERRGhZJ6A1V5TNbeXlj/2Dr/AqyyYecDJxTTIRCh3h+W/BdzIyTYaaLX6eviHmJnE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
