appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: g+Xh+Px7Jti81LF2jtw5KyrK0D6HpXtkCCbee3RDUTGt588WLSEzBrIRoYuVeiMBvLu7fgTRH0BzCivj37jopfjpDn7ePMHHlwhBa8IyEJqGUonPCm0HdnGkhMczRRwjCJGgmVvPZ89htfMTzIYR4JOAAxLJtLcj3oOI5aa6ClJOTgRGoa/Puzma/zLhvquAnZH3NE613wxs2cX4I9Kv0kUR19wVV/0meahDzalva8XWPEzqCKlVj75FntsfpkMe3Bwra2GENKZa0+phCr2oNsSjROdiJYXXJLOvF0XEibNk7nZOrofbO8W9mrU5COqOgIRqWMVOsqmJ2DHl3cipmVJcocOH2SKYIZNSamxQMn34peJ3gxNThVG16lOBzv1rtiiK5AToyQdK5EBAYCW5ctUUpZQBVcRk+o5SbOPIt2S8KoftsGENt0sNu99VS5J3G9lR9OBlD6ChOc5Vt9Dm+kiUss6fRq518CCYqndKhZf/tEbGpIQZI1ouTEqBbVlApvCaj5/hb33/1sT3H56RXlh8Mj6WpM2YGfJMtWQoFf19hANAUuNmV0cyxnEwUjpuqSIum0f5ynTWLEmmFtap6fXXyK4IZAztw3m6RtXSsy00z3tEj4n/QECdNeOwb10WzbwozhLwvzl8KgoNl2pNFitdhWrTSPP8ElrEFOnFFF4=}
