travis:
  secure:
    BINSTAR_TOKEN: Dtbin1VClI85Yfh1UupWGLVH+iFvYREImWKg4gJ4/N8TxzpdcVzBYsIHwl6FNP0urY4U+O9GAgjrLWVlsGKtc5x79kU1KGacVx9exJQsHvksjnoY9Xupxcw2mCllUe3r6aRQVNpI+6cp6TSsnZZtVSGl9BcR0Oq+HIzFIQ0kz943XA5ax8Xo+75qRhJJlD5d27dXF7HGhumaT5oQEHBByc1SVMuZSBVXcyEpXnWVQ5WGM1N2E+Y3dvvVk4RoLxl8UuYgoaGVsMaQBdT2Ng+1VPIhgZF61P0RBsZTqzihn9bSKnD1Ef73YvROmzemRVPVDOkKs3fnAytSHNEv7JDut4V9qHHPg343zqXzq+8Oj2GII3NgT3CHRYMQBolv4M8nAPWv5ZHX4S/dJXGAPGeyAcXJ2UvwIiCSqQLrXj3FtgiUYHEc2cJgiTWkwdil/ENVBeYUi/2HByL/PhSDFE0pr4GFv0/xuhrLxmvRvOkV6YUZ+Y7D7vV00Om9mV9PdkfO0AqjoGA+p2/+s19fAN3AJQidmMDOoMOPLFVtc+0xCdirB/MhBX1B8yic1YpOH1qCC1+WG85Nw+bD5CdGt3VD374+quByeGyKIdmq/TS8I7HIyUNzZqo9yE2yae2zuf6eX9qKF0jNMFRBVSGCGm9Fp/dpgTJxgA2uUeYENw+/FyU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
